### ISSUE TITLE
App Crash on Npm run on WLS

### ISSUE THREAD

**Issue by alexanderdevm** [jamrizzi/trailblazer#3]
I go the following error after trying to npm start the project

 ```
npm start

> trailblazer@0.0.0 start /Documents/Dev/trailblazer
> node ./node_modules/nodemon/bin/nodemon -e js -x 'npm run lint && node ./node_modules/babel-cli/bin/babel-node server.js || exit 1'


[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run lint && node ./node_modules/babel-cli/bin/babel-node server.js || exit 1`

> trailblazer@0.0.0 lint /Documents/Dev/trailblazer
> node ./node_modules/eslint/bin/eslint .


/Documents/Dev/trailblazer/doc/doc-filelist.js
  1:1  error  Unexpected var, use let or const instead       no-var
  1:2  error  Newline required at end of file but not found  eol-last
  1:5  error  'tree' is defined but never used               no-unused-vars
  1:9  error  Infix operators must be spaced                 space-infix-ops

/Documents/Dev/trailblazer/doc/doc-script.js
    9:1   error    Unexpected var, use let or const instead         no-var
   11:25  error    'defaultSidebar' is not defined                  no-undef
   23:3   error    Unexpected var, use let or const instead         no-var
   24:3   error    Unexpected var, use let or const instead         no-var
   39:1   warning  Line 39 exceeds the maximum line length of 100   max-len
   53:3   error    Unexpected var, use let or const instead         no-var
   66:3   error    Unexpected var, use let or const instead         no-var
   78:3   error    Unexpected var, use let or const instead         no-var
  101:3   error    Unexpected var, use let or const instead         no-var
  102:3   error    Unexpected var, use let or const instead         no-var
  108:5   error    Unexpected var, use let or const instead         no-var
  109:10  error    Unexpected var, use let or const instead         no-var
  110:1   warning  Line 110 exceeds the maximum line length of 100  max-len
  115:10  error    Unexpected var, use let or const instead         no-var
  121:10  error    Unexpected var, use let or const instead         no-var
  122:1   warning  Line 122 exceeds the maximum line length of 100  max-len
  161:3   error    Unexpected var, use let or const instead         no-var
  162:3   error    Unexpected var, use let or const instead         no-var
  165:8   error    Unexpected var, use let or const instead         no-var
  182:3   error    Unexpected var, use let or const instead         no-var
  183:3   error    Unexpected var, use let or const instead         no-var
  186:8   error    Unexpected var, use let or const instead         no-var
  191:5   error    Unexpected var, use let or const instead         no-var
  219:12  error    'tree' is not defined                            no-undef
  219:18  error    'relativeDir' is not defined                     no-undef
  219:31  error    'thisFile' is not defined                        no-undef

✖ 30 problems (27 errors, 3 warnings)


npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! trailblazer@0.0.0 lint: `node ./node_modules/eslint/bin/eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trailblazer@0.0.0 lint script 'node ./node_modules/eslint/bin/eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trailblazer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/eslint/bin/eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trailblazer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trailblazer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Documents/Dev/trailblazer/npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

npm log file
```
 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'lint' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle trailblazer@0.0.0~prelint: trailblazer@0.0.0
6 silly lifecycle trailblazer@0.0.0~prelint: no script for prelint, continuing
7 info lifecycle trailblazer@0.0.0~lint: trailblazer@0.0.0
8 verbose lifecycle trailblazer@0.0.0~lint: unsafe-perm in lifecycle true
9 verbose lifecycle trailblazer@0.0.0~lint: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/Documents/Dev/trailblazer/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/Documents/Dev/
10 verbose lifecycle trailblazer@0.0.0~lint: CWD: /Documents/Dev/trailblazer
11 silly lifecycle trailblazer@0.0.0~lint: Args: [ '-c', 'node ./node_modules/eslint/bin/eslint .' ]
12 silly lifecycle trailblazer@0.0.0~lint: Returned: code: 1  signal: null
13 info lifecycle trailblazer@0.0.0~lint: Failed to exec lint script
14 verbose stack Error: trailblazer@0.0.0 lint: `node ./node_modules/eslint/bin/eslint .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid trailblazer@0.0.0
16 verbose cwd /Documents/Dev/trailblazer
17 error Linux 4.4.0-43-Microsoft
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error trailblazer@0.0.0 lint: `node ./node_modules/eslint/bin/eslint .`
22 error Exit status 1
23 error Failed at the trailblazer@0.0.0 lint script 'node ./node_modules/eslint/bin/eslint .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the trailblazer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./node_modules/eslint/bin/eslint .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs trailblazer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls trailblazer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jamrizzi** [comment]
That's because the linting is failing. I like to lint my code during development. I'm using different linting rules than the official trailsjs team. You can fix it by conforming to my linting rules, enabling different linting rules, or disabling linting. If you want to disable linting, change the "start" command in the package json to the following . . .

```json
{
. . .
    "scripts": {
        "start": "node ./node_modules/babel-cli/bin/babel-node server.js",
. . .
    }
}
```
